### ISSUE TITLE
Repoman fails to launch after upgrading from 20.04 to 20.10

### ISSUE THREAD

**Issue by ThanosFisherman** [pop-os/repoman#80] opened 2020-10-24 10:40 UTC
Settings menu from pop shop can not be opened. I found out there is an issue with Repoman after upgrading from popos 20.04 to 20.10. 

When I try to launch Repoman from command line I get the following errors.

```
(repoman:9725): Gtk-CRITICAL **: 13:39:28.294: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/repoman/main.py", line 37, in do_activate
    self.win = Window()
  File "/usr/lib/python3/dist-packages/repoman/window.py", line 36, in __init__
    self.stack = Stack(self)
  File "/usr/lib/python3/dist-packages/repoman/stack.py", line 58, in __init__
    self.list_all = List(self)
  File "/usr/lib/python3/dist-packages/repoman/list.py", line 42, in __init__
    self.sp = SoftwareProperties()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 111, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 605, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 91, in get_sources
    raise NoDistroTemplateException(
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Pop/groovy
```

**Comment by Bananas-Are-Yellow** [comment] 2020-10-24 12:19
Same here, for both of my machines that I have just updated. Same traceback.

**Comment by mike-to-spec** [comment] 2020-10-24 17:07
Look in your `/etc/apt/sources.list.d` directory, there may be some 0byte files. Move it out and then try again, it should work. 

A bunch of folks have this same issue and moving out 0byte files fixed it. https://www.reddit.com/r/pop_os/comments/jgout0/pop_os_2010_released/g9ruoj2/

**Comment by ThanosFisherman** [comment] 2020-10-24 18:28
There was indeed a 0-byte file in `/etc/apt/sources.list.d` I deleted it but the problem wasn't solved. Still the same error when launching repoman.

**Comment by Aarivvk** [comment] 2020-10-26 11:29
No 0-byte file in /etc/apt/sources.list.d , repoman still crashes with above mentioned error.

**Comment by bartlebee13** [comment] 2020-10-28 00:59
I'm having this exact same problem. I posted about it on the [pop-planet forums](https://pop-planet.info/forums/threads/pop-_shop-settings-button-not-working-after-20-10-upgrade.1098/#post-5117). 

Any insights into how to fix this?

**Comment by ThanosFisherman** [comment] 2020-10-28 06:39
I just couldn't wait for a solution and did a fresh install of Pop!_os 20.10. Now everything is back to normal..

**Comment by bartlebee13** [comment] 2020-10-28 07:06
Damn I really don't want to have to reinstall the OS. Thanks for the update

**Comment by mmstick** [comment] 2020-10-28 07:08
No need to reinstall. Remove any empty files from `/etc/apt/sources.list.d/` and you should be good

**Comment by bartlebee13** [comment] 2020-10-28 07:15
this is not the same issue as the empty files issue:

```
raise NoDistroTemplateException(
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Pop/groovy
```

its a different error. I have no empty files in /etc/apt/sources.list.d/ to delete

**Comment by isantop** [comment] 2020-10-29 23:30
I think this was being caused by an incomplete upgrade or by repoman being out of date, as it references SoftwareProperties in the traceback (whereas Repoman on 20.10 should be using exclusively Repolib instead, not SoftwareProperties).

@gumballdead Please try updating all software packages in your system and try again

**Comment by bartlebee13** [comment] 2020-10-29 23:34
@isantop do you mean apt-get update and apt-get upgrade? What version of repoman has the fix? Because repoman updated a couple hours ago but I'm still am seeing the same issue

**Comment by bartlebee13** [comment] 2020-10-29 23:40
I just ran apt-get update and upgrade, there was a popshell update.

`repoman is already the newest version (2.0.0~1603825555~20.10~20bd07d)`

repoman terminal output:
```2020-10-29 18:38:40,389 repoman      DEBUG    Logging established
2020-10-29 18:38:40,541 repoman.Repo DEBUG    Logging established
2020-10-29 18:38:40,715 repoman.Settings DEBUG    Logging established.
2020-10-29 18:38:40,717 repoman.Settings DEBUG    Installation changed, regenerating list
2020-10-29 18:38:40,718 repoman.Settings DEBUG    Component universe is enabled
2020-10-29 18:38:40,718 repoman.Settings DEBUG    Component restricted is enabled
2020-10-29 18:38:40,718 repoman.Settings DEBUG    Component multiverse is enabled
2020-10-29 18:38:40,719 repoman.Settings DEBUG    Adding mirrors
2020-10-29 18:38:40,719 repoman.Settings DEBUG    Creating entry for None
2020-10-29 18:38:40,727 repoman.Settings DEBUG    Mirror found: http://us.archive.ubuntu.com/ubuntu/
2020-10-29 18:38:40,727 repoman.Settings DEBUG    Creating entry for http://us.archive.ubuntu.com/ubuntu/
2020-10-29 18:38:40,727 repoman.Settings DEBUG    Mirror http://us.archive.ubuntu.com/ubuntu/ is the only mirror

(repoman:43233): Gtk-CRITICAL **: 18:38:40.728: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed
2020-10-29 18:38:40,728 repoman.Settings DEBUG    Monitor Created: <__gi__.GInotifyFileMonitor object at 0x7fe7fce99200 (GInotifyFileMonitor at 0x23920b0)>
2020-10-29 18:38:40,728 repoman.Updates DEBUG    Logging established
2020-10-29 18:38:40,729 repoman.Updates DEBUG    init_distro
2020-10-29 18:38:40,729 repoman.Updates DEBUG    Monitor Created: <__gi__.GInotifyFileMonitor object at 0x7fe7fce99540 (GInotifyFileMonitor at 0x2392550)>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/repoman/main.py", line 37, in do_activate
    self.win = Window()
  File "/usr/lib/python3/dist-packages/repoman/window.py", line 36, in __init__
    self.stack = Stack(self)
  File "/usr/lib/python3/dist-packages/repoman/stack.py", line 58, in __init__
    self.list_all = List(self)
  File "/usr/lib/python3/dist-packages/repoman/list.py", line 42, in __init__
    self.sp = SoftwareProperties()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 111, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 605, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 91, in get_sources
    raise NoDistroTemplateException(
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Pop/groovy```

**Comment by isantop** [comment] 2020-10-29 23:59
You have some issues with some of your system packages, probably `python3-apt`. That appears to be what's causing this issue for you. 

#85 Will remove the stray SoftwareProperties code from Repoman 2.0.0, which will "fix" this issue with repoman, however, you will still have this problem with other tools using SoftwareProperties (like `add-apt-repository`). In Pop you can use `apt-manage` to perform all of `add-apt-repository`'s utility, however that doesn't change the fact that there are errors in your installation, possibly caused by an incomplete or otherwise failed upgrade.

**Comment by isantop** [comment] 2020-10-30 00:02
What are you getting for the output of `apt policy python-apt-common python3-apt pop-default-settings`?

**Comment by bartlebee13** [comment] 2020-10-30 00:06
```
python-apt-common:
  Installed: 2.1.2pop0~1587756471~20.04~cd2988e
  Candidate: 2.1.2pop0~1587756471~20.04~cd2988e
  Version table:
     2.1.3ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/main amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu groovy/main i386 Packages
 *** 2.1.2pop0~1587756471~20.04~cd2988e 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
python3-apt:
  Installed: 2.1.2pop0~1587756471~20.04~cd2988e
  Candidate: 2.1.2pop0~1587756471~20.04~cd2988e
  Version table:
     2.1.3ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/main amd64 Packages
 *** 2.1.2pop0~1587756471~20.04~cd2988e 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
pop-default-settings:
  Installed: 4.0.6~1602945781~20.10~1a67c98
  Candidate: 4.0.6~1602945781~20.10~1a67c98
  Version table:
 *** 4.0.6~1602945781~20.10~1a67c98 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
     4.0.6~1602024706~20.04~b78b849 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages

```

**Comment by ThanosFisherman** [comment] 2020-10-30 00:08
For what is worth I also had an issue with `libhandy-1-0 groovy` and gnome-contacts and some held back (or broken) packages.

Sorry I can't be more helpful I installed a fresh copy of pop_os.

**Comment by isantop** [comment] 2020-10-30 00:10
@gumballdead Your `python3-apt` and `python-apt-common` are out of date. It looks like your upgrade failed, at least partially, because your system still has focal repositories. 

What is the output you're getting of `apt-manage list --verbose --legacy`

**Comment by bartlebee13** [comment] 2020-10-30 00:12
@isantop  I thought I might have had a failed or incomplete upgrade and I was originally skeptical about upgrading from 20.04 to 20.10 due to all the issues people were talking about on the original reddit thread. But I was also experiencing the random freezing issue on 20.04 with the old kernel.

So after I saw this post: https://github.com/pop-os/pop/issues/1172#issuecomment-715556395 @mmstick assured me that it would be safe to upgrade to the new 20.10 version so I ran these commands:

```
sudo apt-get update
sudo apt-get full-upgrade
pop-upgrade release upgrade
```
when I initially did the upgrade.

I ran `pop-upgrade release repair` afterwards to try to fix it.

**Comment by isantop** [comment] 2020-10-30 00:13
I can help you get your system fixed, but I need to know the output of the above command

**Comment by bartlebee13** [comment] 2020-10-30 00:14
ouput of `apt-manage list --verbose --legacy`


```
Configured sources:
system - Pop_OS System Sources
Name: Pop_OS System Sources
Enabled: yes
Types: deb deb-src
URIs: http://us.archive.ubuntu.com/ubuntu/
Suites: groovy groovy-security groovy-updates groovy-backports
Components: main restricted universe multiverse
X-Repolib-Default-Mirror: http://us.archive.ubuntu.com/ubuntu/

pop-os-apps - Pop_OS Apps
Name: Pop_OS Apps
Enabled: yes
Types: deb
URIs: http://apt.pop-os.org/proprietary
Suites: groovy
Components: main

openrazer-ubuntu-stable-focal - ppa-launchpad-net-openrazer-stable-ubuntu
Name: ppa-launchpad-net-openrazer-stable-ubuntu
Enabled: yes
Types: deb
URIs: http://ppa.launchpad.net/openrazer/stable/ubuntu
Suites: focal
Components: main

beekeeper-studio - dl-bintray-com-beekeeper-studio-releases
Name: dl-bintray-com-beekeeper-studio-releases
Enabled: yes
Types: deb
URIs: https://dl.bintray.com/beekeeper-studio/releases
Suites: disco
Components: main

umang-ubuntu-indicator-stickynotes-focal - ppa-launchpad-net-umang-indicator-stickynotes-ubuntu
Name: ppa-launchpad-net-umang-indicator-stickynotes-ubuntu
Enabled: yes
Types: deb
URIs: http://ppa.launchpad.net/umang/indicator-stickynotes/ubuntu
Suites: focal
Components: main

polychromatic-ubuntu-stable-focal - ppa-launchpad-net-polychromatic-stable-ubuntu
Name: ppa-launchpad-net-polychromatic-stable-ubuntu
Enabled: yes
Types: deb
URIs: http://ppa.launchpad.net/polychromatic/stable/ubuntu
Suites: focal
Components: main

pop-os-ppa - Pop_OS PPA
Name: Pop_OS PPA
Enabled: yes
Types: deb deb-src
URIs: http://ppa.launchpad.net/system76/pop/ubuntu
Suites: groovy
Components: main

vscode - packages-microsoft-com-repos-vscode
Name: packages-microsoft-com-repos-vscode
Enabled: yes
Types: deb
URIs: http://packages.microsoft.com/repos/vscode
Suites: stable
Components: main
Architectures: amd64

sublime-text - download-sublimetext-com
Name: download-sublimetext-com
Enabled: yes
Types: deb
URIs: https://download.sublimetext.com/
Suites: apt/stable/
Components:

teejee2008-ubuntu-timeshift-focal - ppa-launchpad-net-teejee2008-timeshift-ubuntu
Name: ppa-launchpad-net-teejee2008-timeshift-ubuntu
Enabled: yes
Types: deb
URIs: http://ppa.launchpad.net/teejee2008/timeshift/ubuntu
Suites: focal
Components: main

slack - packagecloud-io-slacktechnologies-slack-debian
Name: packagecloud-io-slacktechnologies-slack-debian
Enabled: yes
Types: deb
URIs: https://packagecloud.io/slacktechnologies/slack/debian/
Suites: jessie
Components: main

google-chrome - dl-google-com-linux-chrome-deb
Name: dl-google-com-linux-chrome-deb
Enabled: yes
Types: deb
URIs: http://dl.google.com/linux/chrome/deb/
Suites: stable
Components: main
Architectures: amd64

system76-ubuntu-pop-focal - ppa-launchpad-net-system76-pop-ubuntu
Name: ppa-launchpad-net-system76-pop-ubuntu
Enabled: yes
Types: deb deb-src
URIs: http://ppa.launchpad.net/system76/pop/ubuntu
Suites: focal
Components: main


 Legacy sources.list entries:

deb http://us.archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse
deb-src http://us.archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse
deb http://us.archive.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
deb-src http://us.archive.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
deb http://us.archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse
deb-src http://us.archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse
deb http://us.archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
deb-src http://us.archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
deb http://apt.pop-os.org/proprietary focal main
# deb-src http://apt.pop-os.org/proprietary focal main
deb [arch=amd64] https://deb.tableplus.com/debian tableplus main
# deb-src [arch=amd64] https://deb.tableplus.com/debian tableplus main
deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
# deb-src [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
deb https://dl.winehq.org/wine-builds/ubuntu/ focal main
# deb-src https://dl.winehq.org/wine-builds/ubuntu/ focal main
deb https://dl.bintray.com/loadimpact/deb stable main

The following files have formatting errors:
/etc/apt/sources.list.d/teamviewer.list

Details for the failing files:
/etc/apt/sources.list.d/teamviewer.list:
###   TeamViewer DEB repository list

### NOTE: Manual changes to this file
###        - prevent it from being updated by TeamViewer package updates
###        - will be lost after using the 'teamviewer repo' command
###       The original file can be restored with this command:
###       cp /opt/teamviewer/tv_bin/script/teamviewer.list /etc/apt/sources.list.d/teamviewer.list
###       which has the same effect as 'teamviewer repo default'

### NOTE: It is preferred to use the following commands to edit this file:
###       teamviewer repo                - show current repository configuration
###       teamviewer repo default        - restore default configuration
###       teamviewer repo disable        - disable the repository
###       teamviewer repo stable         - make all regular TeamViewer packages available (default)
###       teamviewer repo preview        - additionally, make feature preview packages available
###       teamviewer repo development    - additionally, make the latest development packages available


deb https://linux.teamviewer.com/deb stable main

# deb https://linux.teamviewer.com/deb preview main
# deb https://linux.teamviewer.com/deb development main

Stack Trace:
  File "/usr/lib/python3/dist-packages/repolib/__init__.py", line 77, in get_all_sources
    source.load_from_file()
  File "/usr/lib/python3/dist-packages/repolib/legacy_deb.py", line 129, in load_from_file
    deb_src = deb.DebLine(line)
  File "/usr/lib/python3/dist-packages/repolib/deb.py", line 54, in __init__
    self._parse_debline(self.deb_line)
  File "/usr/lib/python3/dist-packages/repolib/deb.py", line 82, in _parse_debline
    self._validate(line)
  File "/usr/lib/python3/dist-packages/repolib/deb.py", line 133, in _validate
    raise util.RepoError(

```

**Comment by isantop** [comment] 2020-10-30 00:32
Okay, first you'll need to paste the following into your terminal and press enter:
```
sudo mv /etc/apt/sources.list /etc/apt/sources.list.save && echo "## This file is deprecated in Pop!_OS. 
## See `man deb822` and /etc/apt/sources.list.d/system.sources.
" | sudo tee /etc/apt/sources.list
```
Then press enter, and enter your password when prompted. This will make a backup of your current sources in case of a problem, and then replace your sources.list with the default file.

Then, the following commands should fix your software sources and attempt to finish your upgrade:
```
sudo apt-manage add 'deb [arch=amd64] https://deb.tableplus.com/debian tableplus main' --name TablePlus
sudo apt-manage add 'deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable' --name Docker
sudo apt-manage add 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main' --name Wine
sudo apt-manage add 'deb https://dl.bintray.com/loadimpact/deb stable main' --name "Load Impact"
sudo apt-manage remove system76-ubuntu-pop-focal
sudo apt update
sudo apt full-upgrade
```
They will re-add your custom repositories, remove the errant pop focal repository, and then attempt the upgrade.

**Comment by bartlebee13** [comment] 2020-10-30 00:40
@isantop thank you so much for your help. that worked for me

**Comment by isantop** [comment] 2020-10-30 19:32
I'm going to close this issue now, since this should now be fixed with the latest repolib and repoman

**Closed as completed by isantop** 2020-10-30 19:32 UTC
Labels: bug, APT
