### ISSUE TITLE
Crash when opening if an empty file exists inside of sources.list.d

### ISSUE THREAD

**Issue by Tomoghno** [pop-os/repoman#79] opened 2020-10-23 19:26 UTC
(repoman:18118): Gtk-CRITICAL **: 00:49:46.342: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/repoman/main.py", line 37, in do_activate
    self.win = Window()
  File "/usr/local/lib/python3.8/dist-packages/repoman/window.py", line 36, in __init__
    self.stack = Stack(self)
  File "/usr/local/lib/python3.8/dist-packages/repoman/stack.py", line 58, in __init__
    self.list_all = List(self)
  File "/usr/local/lib/python3.8/dist-packages/repoman/list.py", line 134, in __init__
    self.generate_entries()
  File "/usr/local/lib/python3.8/dist-packages/repoman/list.py", line 211, in generate_entries
    self.sources = repo.get_all_sources()
  File "/usr/local/lib/python3.8/dist-packages/repoman/repo.py", line 157, in get_all_sources
    source.load_from_file()
  File "/usr/lib/python3/dist-packages/repolib/legacy_deb.py", line 134, in load_from_file
    self.load_from_sources()
  File "/usr/lib/python3/dist-packages/repolib/legacy_deb.py", line 110, in load_from_sources
    self.make_names()
  File "/usr/lib/python3/dist-packages/repolib/legacy_deb.py", line 80, in make_names
    self.name = self.sources[0].make_name()
IndexError: list index out of range

**Comment by geodro** [comment] 2020-10-23 20:20
Can confirm

`(repoman:23167): Gtk-CRITICAL **: 23:19:07.464: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/repoman/main.py", line 37, in do_activate
    self.win = Window()
  File "/usr/lib/python3/dist-packages/repoman/window.py", line 36, in __init__
    self.stack = Stack(self)
  File "/usr/lib/python3/dist-packages/repoman/stack.py", line 58, in __init__
    self.list_all = List(self)
  File "/usr/lib/python3/dist-packages/repoman/list.py", line 134, in __init__
    self.generate_entries()
  File "/usr/lib/python3/dist-packages/repoman/list.py", line 211, in generate_entries
    self.sources = repo.get_all_sources()
  File "/usr/lib/python3/dist-packages/repoman/repo.py", line 157, in get_all_sources
    source.load_from_file()
  File "/usr/lib/python3/dist-packages/repolib/legacy_deb.py", line 134, in load_from_file
    self.load_from_sources()
  File "/usr/lib/python3/dist-packages/repolib/legacy_deb.py", line 110, in load_from_sources
    self.make_names()
  File "/usr/lib/python3/dist-packages/repolib/legacy_deb.py", line 80, in make_names
    self.name = self.sources[0].make_name()
IndexError: list index out of range`

**Comment by jacobgkau** [comment] 2020-10-23 22:45
I'm able to reproduce this `IndexError` crash using these commands:

```
sudo touch /etc/apt/sources.list.d/empty.list
repoman
```

**Comment by jacobgkau** [comment] 2020-10-23 22:49
This is a duplicate of https://github.com/pop-os/repoman/issues/78.

**Closed** 2020-10-29 23:29 UTC
